### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by AmingWu** [Sha-Lab/babywalk#1]
This is a good work. Could I use a 1080GPU with 12GB memory to reproduce your result? And How long does your model need to train?

**Comment by Bill1235813** [comment]
Yes, you can. It depends on the dataset you are training on, take R2R as an example.

For 12GB GPU, choose batch size 64. The imitation learning phase takes about 8 hours. The curriculum reinforcement learning phase takes about 8 hours for each curriculum.

For R4R, R6R or R8R, you need to reduce the batch size a little, like to 48. And the training takes a bit longer.
