### ISSUE TITLE
Question about BabyWalk results on the CVDN Leaderboard

### ISSUE THREAD

**Issue by g-karthik** [Sha-Lab/babywalk#2]
I noticed your two submissions on the CVDN leaderboard. Could you please point me to the code and instructions to replicate those results?

Also, I'm a bit confused because your paper is on VLN, but I do not see any BabyWalk submissions on the VLN leaderboard itself. Could you please explain?

**Comment by Bill1235813** [comment]
Dear Karthik,

Thanks for your interest in our work. We are running on experiments to prepare a Journal submission for our work, which includes new evaluation tasks, such as CVDN. The BabyWalk entry on the leaderboard you see is a straightforward application of this codebase, but on the CVDN dataset. 

Unfortunately, before the acceptance of the our work, we would not be able to release the code with respect to the CVDN part. Hope you would understand this.

Best,
Bill

**Comment by g-karthik** [comment]
@Bill1235813 sure, no worries, although I personally think it should be fine to release the code if it is only a straightforward application of the ACL paper with no novel, CVDN-specific additions.

Can you also please share why there is no entry for BabyWalk on the VLN leaderboard? I got confused because the BabyWalk paper is written for VLN, and it was surprising to see no leaderboard entry for VLN, and instead for CVDN.

Thanks!

**Comment by Bill1235813** [comment]
Hi **@g-karthik** ,

Our main idea of the ACL paper is to help VLN agent to improve the generalization over different task horizons. Therefore, our focus is the **Room-4-Room** (and Room-6-Room, Room-8-Room), which do not have a leaderboard to upload the result.

**Comment by g-karthik** [comment]
@Bill1235813 From what I see in your paper, you trained on R2R also, and measured out-of-domain generalization from R4R --> R2R.

So I'm not sure I understand your explanation.

Also, I assume you are training with R4R for your CVDN submission as well. But that didn't stop you from submitting to the CVDN leaderboard :)

**Comment by Bill1235813** [comment]
Hi @g-karthik,

“@Bill1235813 From what I see in your paper, you trained on R2R also, and measured out-of-domain generalization from R4R --> R2R.”
Transferring learning from R4R to R2R is obviously going to be inferior to R2R --> R2R without adaptation. The result is not going to be as competitive to other models so there is no point of uploading to leaderboard. Please see Table 5 in the paper.

"Also, I assume you are training with R4R for your CVDN submission as well. But that didn't stop you from submitting to the CVDN leaderboard :)"
As already mentioned, the results on CVDN is based on a extension of the original paper. It is not trained on R4R and transferred to CVDN, but directly training on the CVDN dataset.

**Comment by g-karthik** [comment]
> Transferring learning from R4R to R2R is obviously going to be inferior to R2R --> R2R without adaptation. The result is not going to be as competitive to other models so there is no point of uploading to leaderboard.

In my previous message, when I said "I assume you are training with R4R for your CVDN submission as well", I meant for your new journal paper submission for a similar analysis as Table 5 and Table 2, not the leaderboard submission.

The actual VLN leaderboard submission could still be BabyWalk R2R --> R2R. My question is, why was that model not submitted to the VLN leaderboard (i.e., Table 5 3rd row, with SR=43.8, CLS=54.4, etc.)? Does it mean the BabyWalk model is not SOTA for R2R on the leaderboard metrics?

**Comment by hexiang-hu** [comment]
Hi @g-karthik: 

> The actual VLN leaderboard submission could still be BabyWalk R2R --> R2R. My question is, why was that model not submitted to the VLN leaderboard (i.e., Table 5 3rd row, with SR=43.8, CLS=54.4, etc.)? Does it mean the BabyWalk model is not SOTA for R2R on the leaderboard metrics?

Thanks a lot for your interest in our work and all your previous comments. If I understand correctly, you would like to see our model trained on R2R and evaluated on the standard VLN benchmark. We did not do this because of the following reason:

As you might already noticed, Babywalk is not the best model to explore ''shortcuts'' in the data (as what was shown in Jain et. al. ACL 2019) and achieve a superior success rate. Instead, Babywalk is better at following long instructions and produce high-fidelity paths. Therefore it generates a better result in terms of the instruction following metrics such as CLS, or sDTW. 

Unfortunately, as far as I know, the current VLN leaderboard focuses on evaluating the model's capability in goal-reaching and does not support the above two evaluation metrics. We believe that our model would not be able to outperform existing leaderboard results in terms of success rate and therefore we did not submit our results to the leaderboard.

Please let me know if you have any other questions.  

Best,

**Comment by g-karthik** [comment]
@hexiang-hu thanks for the detailed response! When you say "instruction following", that is agnostic to length of the instruction, right? So if I understand correctly, BabyWalk is better at **long** instruction following (as in CVDN, treating the entire dialog history as an instruction), but poor at **short** instruction following (as in VLN)?
