### ISSUE TITLE
How to visualize the trajectory based the instruction?

### ISSUE THREAD

**Issue by haofanwang** [Sha-Lab/babywalk#3]
Hi, @Bill1235813 , thanks for sharing this great work.

I want to visualize the trajectory, e.g the picture in your paper. How can I do this? Do I need to download Matterport3D dataset? If possible, could you share your visualization scripts? Thanks.

**Comment by Bill1235813** [comment]
Hi @haofanwang, 

Thanks for your interest in our work. Yes, you need to download Matterport3D dataset first. 

For top-view visualization, we use [mpview](https://github.com/niessner/Matterport/tree/master/code/gaps/apps/mpview) visualization tool. For trajectory visualization, the code is at [graph_utils.py](../tree/master/tasks/R4R/graph_utils.py)

Best,
Bill

**Comment by haofanwang** [comment]
Great! I'll take a look.

**Comment by lkhazyf** [comment]
您好，请问您画出来轨迹图了吗？graph_utils.py里面draw函数的输入都是哪些啊？我的意思是怎么得到的，或者您可以发我一份吗？我的邮箱是2647619156@qq.com，非常谢谢！
