### ISSUE TITLE
Release of Appendix A. Details on BABY-STEP Identification

### ISSUE THREAD

**Issue by SouLeo** [Sha-Lab/babywalk#4]
Hello, I'm very interested in the work put forth by this paper and would like further clarification on how the BABY-STEP identifications were made.

I have viewed Appendix A but had trouble understanding the full implementation from 

1. Split sentence and chunk phrases 
2. Curate noun phrases on stop words were made

I'm primarily interested in the grammar productions used for identifying noun phrases. I had difficulty locating the specific code in this repository, so any direction would be greatly appreciated.

Thank you.

**Comment by Bill1235813** [comment]
Thanks for your interest in our work.

Please see [here](https://drive.google.com/file/d/1soXYE-IMveMpvjAi6lNSpJURE3B4IYk3/view?usp=sharing) for the landmark alignment code.

**Comment by SouLeo** [comment]
Thank you! 🙏
